#!/usr/bin/env perl
use strict;
use warnings;

# Use the libs specific to this repo
BEGIN { unshift @INC => './lib' if -e './env_config.pm' && -d './lib' }

use Ndn::Environment;
use Ndn::Environment::CLI;

my $env = Ndn::Environment->singleton;
$env->load_plugins;

my $cli = Ndn::Environment::CLI->singleton;
$cli->load_plugins;

$cli->run(@ARGV);

1;
