#!/usr/bin/env perl

use strict;
use warnings;


# Use the libs specific to this repo
BEGIN { unshift @INC => './lib' if -e './env_config.pm' && -d './lib' }

use Ndn::Environment::Deps bootstrap => 'prompt';
use Ndn::Environment;
use Ndn::Environment::App;

Ndn::Environment->singleton->load_plugins;
Ndn::Environment::App->run;

!!42;
